package com.n75jr.battleship.bot;

public enum BotState {

    UNDEFINED,
    DEFAULT,
    MAIN_MENU,
    PLAY_MENU,
    PLAY_MENU_MODE,
    PLAY_OFFLINE_GAME_SHIP_PLACEMENT,
    PLAY_OFFLINE_GAME_YOUR_MOVE,
    PLAY_OFFLINE_GAME_ENEMY_MOVE,
    PLAY_ONLINE_GAME_SEARCH,
    PLAY_ONLINE_GAME_SHIPS_PLACEMENT,
    PLAY_ONLINE_GAME_SHIPS_PLACEMENT_CONFIRM,
    PLAY_ONLINE_GAME_YOUR_MOVE,
    PLAY_ONLINE_GAME_ENEMY_MOVE,
    PROFILE_INFO,
    RATING_TABLE,
    SETTINGS,
    SETTINGS_OPTIONS,
    SETTINGS_CHANGE_LANGUAGE_SHOW,
    ABOUT,
    PLAY_OFFLINE_GAME,
    LEAVE
}
